function mymobile() {
  document.getElementById("mobile").style.backgroundColor = "#1f222b";
  document.getElementById("mob1").style.color = "#ffcc75";
  document.getElementById("mobile").style.color = "white";
  document.getElementById("super").style.backgroundColor = "#0f1014";
  document.getElementById("sup1").style.color = "#bfdeef";
  document.getElementById("super").style.color = "#bfdeef";
  document.getElementById("premium").style.backgroundColor = "#0f1014";
  document.getElementById("pre1").style.color = "#bfdeef";
  document.getElementById("premium").style.color = "#bfdeef";
  document.getElementById("mo").style.outlineColor = "white";
  document.getElementById("mo-1").style.color = "#fec97c";
  document.getElementById("su").style.outlineColor = "#4b5563";
  document.getElementById("su-1").style.color = "white";
  document.getElementById("pr").style.outlineColor = "#4b5563";
  document.getElementById("pr-1").style.color = "white";
  document.getElementById("checkbox-4").style.display = "block";
  document.getElementById("checkbox-5").style.display = "none";
  document.getElementById("checkbox-6").style.display = "none";
}

function mysuper() {
  document.getElementById("mobile").style.backgroundColor = "#0f1014";
  document.getElementById("mob1").style.color = "#bfdeef";
  document.getElementById("mobile").style.color = "#bfdeef";
  document.getElementById("super").style.backgroundColor = "#1f222b";
  document.getElementById("sup1").style.color = "#ffcc75";
  document.getElementById("super").style.color = "white";
  document.getElementById("premium").style.backgroundColor = "#0f1014";
  document.getElementById("pre1").style.color = "#bfdeef";
  document.getElementById("premium").style.color = "#bfdeef";
  document.getElementById("mo").style.outlineColor = "#4b5563";
  document.getElementById("mo-1").style.color = "white";
  document.getElementById("su").style.outlineColor = "white";
  document.getElementById("su-1").style.color = "#fec97c";
  document.getElementById("pr").style.outlineColor = "#4b5563";
  document.getElementById("pr-1").style.color = "white";
  document.getElementById("checkbox-4").style.display = "none";
  document.getElementById("checkbox-5").style.display = "block";
  document.getElementById("checkbox-6").style.display = "none";
}
function mypremium() {
  document.getElementById("mobile").style.backgroundColor = "#0f1014";
  document.getElementById("mob1").style.color = "#bfdeef";
  document.getElementById("mobile").style.color = "#bfdeef";
  document.getElementById("super").style.backgroundColor = "#0f1014";
  document.getElementById("sup1").style.color = "#bfdeef";
  document.getElementById("super").style.color = "#bfdeef";
  document.getElementById("premium").style.backgroundColor = "#1f222b";
  document.getElementById("pre1").style.color = "#ffcc75";
  document.getElementById("premium").style.color = "white";
  document.getElementById("mo").style.outlineColor = "#4b5563";
  document.getElementById("mo-1").style.color = "white";
  document.getElementById("su").style.outlineColor = "#4b5563";
  document.getElementById("su-1").style.color = "white";
  document.getElementById("pr").style.outlineColor = "white";
  document.getElementById("pr-1").style.color = "#fec97c";
  document.getElementById("checkbox-4").style.display = "none";
  document.getElementById("checkbox-5").style.display = "none";
  document.getElementById("checkbox-6").style.display = "block";
}
function myquarterly() {
  document.getElementById("rate-1").innerHTML = "149";
  document.getElementById("rate-2").innerhtml = "299";
  document.getElementById("rate-3").innerHTML = "499";
  document.getElementById("month-1").innerHTML = "/3Months";
  document.getElementById("month-2").innerHTML = "/3Months";
  document.getElementById("month-3").innerHTML = "/3Months";
  document.getElementById("checkbox-1").style.display = "block";
  document.getElementById("checkbox-2").style.display = "none";
  document.getElementById("checkbox-3").style.display = "none";
  document.getElementById("checkbox-4").style.display = "block";
  document.getElementById("checkbox-5").style.display = "none";
  document.getElementById("checkbox-6").style.display = "none";
  document.getElementById("pl-1").style.color = "white";
  document.getElementById("pl-2").style.color = "#6b7894";
  document.getElementById("pl-3").style.color = "#6b7894";
  document.getElementById("mo").style.outlineColor = "white";
  document.getElementById("su").style.outlineColor = "white";
  document.getElementById("pr").style.outlineColor = "white";
  document.getElementById("mo-1").style.position = "relative";
  document.getElementById("mo-1").style.top = "0px";
  document.getElementById("su-1").style.position = "relative";
  document.getElementById("su-1").style.top = "0px";
  document.getElementById("mo-1").style.color = "#fec97c";
  document.getElementById("su-1").style.color = "#white";
  document.getElementById("pr-1").style.color = "#white";
}
function myyearly() {
  document.getElementById("rate-1").innerHTML = "499";
  document.getElementById("rate-2").innerHTML = "899";
  document.getElementById("rate-3").innerHTML = "1499";
  document.getElementById("month-1").innerHTML = "/Year";
  document.getElementById("month-2").innerHTML = "/Year";
  document.getElementById("month-3").innerHTML = "/Year";
  document.getElementById("checkbox-1").style.display = "none";
  document.getElementById("checkbox-2").style.display = "block";
  document.getElementById("checkbox-3").style.display = "none";
  document.getElementById("checkbox-4").style.display = "block";
  document.getElementById("checkbox-5").style.display = "none";
  document.getElementById("checkbox-6").style.display = "none";
  document.getElementById("pl-1").style.color = "#6b7894";
  document.getElementById("pl-2").style.color = "white";
  document.getElementById("pl-3").style.color = "#6b7894";
  document.getElementById("mo").style.outlineColor = "white";
  document.getElementById("su").style.outlineColor = "white";
  document.getElementById("pr").style.outlineColor = "white";
  document.getElementById("mo-1").style.position = "relative";
  document.getElementById("mo-1").style.top = "0px";
  document.getElementById("su-1").style.position = "relative";
  document.getElementById("su-1").style.top = "0px";
  document.getElementById("mo-1").style.color = "#fec97c";
  document.getElementById("su-1").style.color = "#white";
  document.getElementById("pr-1").style.color = "#white";
}
function mymonthly() {
  document.getElementById("rate-1").innerHTML = "";
  document.getElementById("rate-2").innerHTML = "";
  document.getElementById("rate-3").innerHTML = "299";
  document.getElementById("month-1").innerHTML = "";
  document.getElementById("month-2").innerHTML = "";
  document.getElementById("month-3").innerHTML = "/Month";
  document.getElementById("checkbox-1").style.display = "none";
  document.getElementById("checkbox-2").style.display = "none";
  document.getElementById("checkbox-3").style.display = "block";
  document.getElementById("checkbox-4").style.display = "none";
  document.getElementById("checkbox-5").style.display = "none";
  document.getElementById("checkbox-6").style.display = "block";
  document.getElementById("pl-1").style.color = "#6b7894";
  document.getElementById("pl-2").style.color = "#6b7894";
  document.getElementById("pl-3").style.color = "white";
  document.getElementById("mo").style.outlineColor = "#252833";

  document.getElementById("mo-1").style.position = "relative";
  document.getElementById("mo-1").style.top = "15px";
  document.getElementById("su").style.outlineColor = "#252833";

  document.getElementById("su-1").style.position = "relative";
  document.getElementById("su-1").style.top = "15px";
  document.getElementById("pr").style.outlineColor = "white";
  document.getElementById("pr-1").style.color = "#fec97c";
  document.getElementById("mo-1").style.color = "#6a738c";
  document.getElementById("su-1").style.color = "#6a738c";
}
